# Generated by Django 5.1.5 on 2025-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediatoken',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
